Persisted Queries #93
AlecAivazis/houdini pull request #136
Opened 2021-07-16 09:50 UTC by pixelmund

## This implements persisted queries!

I added a `--persist-output` flag to the `generate` command, which can be used to write a `queryMap` to the provided location in json format.

I'm using the `hashDocument` function again and updated it to use `sha256` instead of `md5` since this is what apollo server expects.

I'm passing the hash to the `environments` fetch function, this opens up for 2 different persisted query approaches.

- [Apollo Style](https://github.com/apollographql/apollo-link-persisted-queries#apollo-engine)
- [Relay Style](https://relay.dev/docs/guides/persisted-queries/)

I personally prefer the `--persist-output` option because i'm not using apollo in any ways but this let's the user decide.

The `--persist-output` flag is not required for the `apollo style`.

I'm open to any changes, renames etc.

2021-07-16 10:06 UTC, pixelmund commented
Uff the tests are broken, probably because adding the `hash` back to the artifacts. I don't really know how to fix those.

2021-07-16 16:00 UTC, AlecAivazis requested changes
Awesome!! Thanks so much for putting this together. It's a bit hard to review with all of the whitespace changes - mind seeing if you can fix them? It looks like jest is leaving down spaces instead of tabs

2021-07-16 16:17 UTC, pixelmund commented
Yeah sure i will fix them on sunday when i got some free time. I had issues with jest and tabs, for some reason switching to spaces on these Files fixed it. But im sure it will work with Tabs too.

2021-07-20 08:21 UTC, pixelmund commented
I will keep this pr as draft until pagination is merged, because there are many changes to the tests.

2021-07-20 16:28 UTC, AlecAivazis commented
Sounds good! the pagination branch also dramatically simplifies the artifact generation logic. Instead of constantly wrestling ASTs it builds up javascript objects and then coverts it to the proper AST in a single step. That lets us share types between the runtime and generation code to make sure everything matches up.

2021-07-29 09:23 UTC, closed without merging