Feat: Export type ConfigFile to enable typable configs + code completion
AlecAivazis/houdini pull request #145
Opened 2021-07-25 09:42 UTC by benbender

Hey,

just a small enhancement to enable typable configs. It's quite nice to have some confidence while changing configs and comes with basically zero cost...

Btw, thanks for your work - its great to expand the svelte-way of tackle modern frontend-problems to the graphql-client! :)

2021-07-25 23:08 UTC, AlecAivazis commented
Oh nice! I like this a lot. I think we can clean it up a bit by exporting the type from `houdini/packages/houdini/cmd/types.ts` instead of the runtime. That should let users type their config file with:

```javascript
/** @type {import('houdini').ConfigFile} */
const config = {
   ...
}
```

2021-07-26 04:47 UTC, benbender commented
Even cleaner and nicer :) Do you want to do it or should I update the PR?

2021-07-26 07:08 UTC, AlecAivazis commented
You can do it if you want otherwise I can pick up the torch between work this week

2021-07-26 16:45 UTC, AlecAivazis commented
What do you think about adding this comment to the default config file stamped out by `init`? It seems like a useful thing to add in general and if i remember correctly, sveltekit also includes the type comment by default. Fwiw, that's defined [here](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini/cmd/init.ts#L142-L148)

2021-07-26 17:03 UTC, benbender commented
I think that everything should be typed in general - and that should more people should be educated that JS also can be typed (with a reasonable editor). So I don't see any (potential) downside in this change and would vote in favor!

2021-07-26 17:16 UTC, AlecAivazis commented
Sweet - feel free to update your PR and then we can merge this in 👍

2021-07-27 19:44 UTC, benbender commented
@AlecAivazis Just had a look and I'm unshure how to tackle this. If I understood the code correctly, the config-file on `houdini init` is generated here https://github.com/AlecAivazis/houdini/blob/c990e0ae66e345e54335d2c6a16ad9e2f322cb9f/packages/houdini/cmd/init.ts#L85 from an object. I don't have a clou how to add a comment without rewriting the whole infrastructure to be template-based...

2021-07-27 19:46 UTC, AlecAivazis commented
@benbender - like I mentioned above, the actual contents for the config file are [here](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini/cmd/init.ts#L142-L148) so you just have to add the comment to both strings so that it shows up in the esm and cjs config files

2021-07-27 19:48 UTC, benbender commented
Nevermind, just saw it - I overlooked the function below and assumed there was some kind of external package generating the file. PR updated...

2021-07-27 19:49 UTC, AlecAivazis requested changes

2021-07-27 19:49 UTC, AlecAivazis commented on packages/houdini/cmd/init.ts
> +		  export default config;
Do we need to define the variable in a separate line from the export? The [sveltekit default config](https://github.com/AlecAivazis/houdini/blob/main/example/svelte.config.js) doesn't seem to do that. I'd prefer to keep it on one line if possible

2021-07-27 19:55 UTC, benbender commented on packages/houdini/cmd/init.ts
> +		  export default config;
I like it that way so you get the documentation/preview/etc (don't know the exact name of those features) by your editor when you hover the var. That's the reason why I normally assign configs first before exporting them...

2021-07-27 19:57 UTC, AlecAivazis commented on packages/houdini/cmd/init.ts
> +		  export default config;
Let's still have it on one line since it seems like an IDE-specific optimization for a particular workflow. For example, I get a very similar experience with ctrl+spacebar in vscode

2021-07-27 20:01 UTC, benbender commented on packages/houdini/cmd/init.ts
> +		  export default config;
Updated

2021-07-27 20:02 UTC, AlecAivazis requested changes

2021-07-27 20:02 UTC, AlecAivazis commented on example/houdini.config.js
> +const config = {
Mind updating the example project aswell? I think it's important to keep that in sync

2021-07-27 20:04 UTC, benbender commented on example/houdini.config.js
> +const config = {
done

2021-07-27 20:08 UTC, AlecAivazis requested changes

2021-07-27 20:08 UTC, AlecAivazis commented on packages/houdini/cmd/init.ts
> +		  `
Sorry for submitting these requests one at a time. Hard to juggle this between work 😅 

I'm not sure this will render correctly - i think you want the comment at the start of the string and then the export at the beginning of the line without any of the white space. You'll also need to update the tests

2021-07-27 20:11 UTC, benbender commented on packages/houdini/cmd/init.ts
> +		  `
Wouldn't do any harm afaik, but fixed anyways.

2021-07-27 23:54 UTC, merged

2021-07-28 00:01 UTC, AlecAivazis commented
Just tested this locally before publishing - you were right, in order to get intellisense we need to add the comment on the variable definition. It doesn't work to comment on the export statement. Going to update this to reflect how you originally had it