Feat: Persisted Queries
AlecAivazis/houdini pull request #148
Opened 2021-07-29 09:26 UTC by pixelmund

I've gone ahead and wrote some docs. Feel free to adjust them however you like or i can do it too. 
I tested the apollo style in the example and it works smoothly.

2021-07-29 18:31 UTC, AlecAivazis requested changes
Overall this looks pretty good! One small tweak/nitpick and we should be able to merge this in really quickly 👍

2021-07-29 18:31 UTC, AlecAivazis commented on packages/houdini-common/src/config.ts
> +	outputPath?: string
Can we rename this to something like `persistedQueryPath`? `outputPath` is pretty generic and will likely confuse me down the line.

2021-07-29 18:31 UTC, AlecAivazis commented on README.md
> +## 🚦&nbsp;&nbsp;Persisted Queries
Thanks for adding this!

2021-07-29 18:49 UTC, pixelmund commented on README.md
> +## 🚦&nbsp;&nbsp;Persisted Queries
:)

2021-07-30 05:11 UTC, AlecAivazis approved these changes
Thanks for making those changes!

2021-07-30 05:11 UTC, merged