Feat: onLoad Hook
AlecAivazis/houdini pull request #149
Opened 2021-07-29 17:49 UTC by pixelmund

Closes #147

2021-07-29 18:26 UTC, AlecAivazis requested changes

2021-07-29 18:26 UTC, AlecAivazis commented on packages/houdini-preprocess/src/transforms/query.test.ts
> +		    _houdini_context.onLoadHook({
Since `onLoad` is async, do we need to `await` this here?

2021-07-29 18:26 UTC, AlecAivazis commented on packages/houdini-preprocess/src/transforms/query.ts
> +				AST.spreadProperty(
I think it would be cleaner if you check for the `onLoadDefinition` before pushing the other values so we don't have to duplicate the actual query responses. Something like

```javscript
if (onLoadDefinition) {
    propsValue.properties.push(...)
}

propsValue.properties.push( ...)
```

2021-07-29 18:30 UTC, pixelmund commented on packages/houdini-preprocess/src/transforms/query.ts
> +				AST.spreadProperty(
You're right😅

2021-07-29 18:31 UTC, pixelmund commented on packages/houdini-preprocess/src/transforms/query.test.ts
> +		    _houdini_context.onLoadHook({
Yeah probably

2021-07-29 18:33 UTC, AlecAivazis commented
We also probably want to add some documentation for this hook. I can take a stab at it after this goes in if you prefer

2021-07-29 18:57 UTC, AlecAivazis requested changes

2021-07-29 18:57 UTC, AlecAivazis commented on packages/houdini/runtime/network.ts
> +		if (result == null || typeof result !== 'object') {
I think we also want to check for `this.continue` here incase the user returns an error from `onLoad`

2021-07-29 18:57 UTC, AlecAivazis commented on packages/houdini-preprocess/src/transforms/query.test.ts
> +		    if (!_houdini_context.continue) {
I think the way this is currently implemented might cause confusing behavior if there is a variable function and `onLoad` defined in the same component. We want to check for `context.continue` after each step so that an error in `onLoad` will prevent the variable function from firing

2021-07-29 19:02 UTC, pixelmund commented on packages/houdini-preprocess/src/transforms/query.test.ts
> +		    if (!_houdini_context.continue) {
Yeah that makes sense

2021-07-30 08:29 UTC, AlecAivazis approved these changes
Sweet! Thanks for getting this out so quickly

2021-07-30 08:29 UTC, merged