Address houdini generate -p errors if schema file doesn't exist
AlecAivazis/houdini pull request #165
Opened 2021-08-23 13:58 UTC by ledesmablt

Bug fixes for #162

```
benj@MacBook ~/projects/houdini/example
fix/issue-162* $ ls schema
index.cjs

benj@MacBook ~/projects/houdini/example
fix/issue-162* $ yarn generate
Error: Schema file does not exist! Create it using houdini generate -p
    at new Config (file:///Users/benj/projects/houdini/packages/houdini/build/cmd.js:688:23)
    at file:///Users/benj/projects/houdini/packages/houdini/build/cmd.js:1067:31
    at step (file:///Users/benj/projects/houdini/packages/houdini/build/cmd.js:346:23)
    at Object.next (file:///Users/benj/projects/houdini/packages/houdini/build/cmd.js:327:53)
    at fulfilled (file:///Users/benj/projects/houdini/packages/houdini/build/cmd.js:317:58)

benj@MacBook ~/projects/houdini/example
fix/issue-162* $ yarn generate -p
Pulled latest schema from http://localhost:4000/graphql
ItemEntry_item
UncompleteItem
ItemUpdate
AllItems
AddItem
NewItem
CompleteItem
DeleteItem
```

2021-08-23 17:04 UTC, AlecAivazis requested changes

2021-08-23 17:04 UTC, AlecAivazis commented on packages/houdini/cmd/main.ts
> -					config.schema = schema
I think this line was dropped, i dont see an equivalent in the rest of the diff

2021-08-24 02:18 UTC, ledesmablt commented on packages/houdini/cmd/main.ts
> -					config.schema = schema
it's on line 49: `config = await getConfig()`

instead of calling `getConfig()` prior to the schema pull, it's called after that. this will load the latest pulled schema that was just written, so no need to overwrite it in the config variable

2021-08-24 06:00 UTC, AlecAivazis commented on packages/houdini/cmd/main.ts
> -					config.schema = schema
Ahhh, right - thanks!

2021-08-24 06:46 UTC, AlecAivazis approved these changes
works like a charm!

2021-08-24 06:46 UTC, merged