Fix #76,#71
AlecAivazis/houdini pull request #77
Opened 2021-05-23 14:46 UTC by pixelmund

Hey, this is my first take on implementing the #76 `pull schema` functionality.
I also included support to read from .graphql and .gql #71 as schemaPath, because i was already on that topic.

Im open for any suggestions and changes, i don't really know how to write tests for this or if you have any tests for commands currently.

2021-05-23 21:41 UTC, AlecAivazis requested changes

2021-05-23 21:41 UTC, AlecAivazis commented on packages/houdini/cmd/main.ts
> +	.option('-p|--pull-schema', 'Pull the latest schema before generating')
Let's change this to `-p, --pull-schema` in order to match the `help` command: 
![image](https://user-images.githubusercontent.com/916317/119277428-81cba580-bbd4-11eb-9453-1c84ba3cc8de.png)

2021-05-23 21:41 UTC, AlecAivazis commented on packages/houdini/cmd/utils/getSchema.ts
> +        process.exit(0);
Looks like prettier needs to be run

2021-05-23 21:41 UTC, AlecAivazis commented on packages/houdini/cmd/utils/getSchema.ts
> +export async function getSchema(url: string, schemaPath: string) {
Thought on renaming this to `writeSchema`? `get` makes me think that the function will return the value

2021-05-23 21:42 UTC, AlecAivazis commented
Thanks for opening this up @pixelmund - just a few changes but we should be able to get this in quickly

2021-05-24 13:48 UTC, pixelmund commented on packages/houdini/cmd/utils/getSchema.ts
> +export async function getSchema(url: string, schemaPath: string) {
You're right i changed it to `writeSchema`.

2021-05-24 16:30 UTC, AlecAivazis commented on example/houdini.config.js
>  	schemaPath: path.resolve('./schema/introspection.json'),
It looks like you removed the `.json` file here but left it in the config. Should this point to `.schema/schema.gql`?

2021-05-24 16:39 UTC, pixelmund commented on example/houdini.config.js
>  	schemaPath: path.resolve('./schema/introspection.json'),
The introspection.json file is still in the schema folder isn't it? I can remove one of them if you like, it was just for demonstration

2021-05-24 16:40 UTC, AlecAivazis commented on example/houdini.config.js
>  	schemaPath: path.resolve('./schema/introspection.json'),
Ahh i see what happened - got confused by github's diff. There is a single green line at the bottom of a lot of red haha. Ignore this :)

2021-05-24 18:41 UTC, AlecAivazis approved these changes
Looks good! Thanks for getting this changes out so quickly

2021-05-24 18:49 UTC, merged

2021-05-24 20:07 UTC, AlecAivazis commented
Just deployed this as `0.5.1` and took the opportunity to remove the `@kit` version tag.

Thanks again!

2021-05-25 07:08 UTC, pixelmund commented
Happy to help!