Refetch queries #57 #86
AlecAivazis/houdini pull request #87
Opened 2021-05-31 11:46 UTC by pixelmund

2021-05-31 16:26 UTC, AlecAivazis requested changes
Thanks for getting this out so quickly @pixelmund! I really appreciate all the work you are putting in on this library. Just a few changes but we should be able to get this in quickly

2021-05-31 16:26 UTC, AlecAivazis commented on packages/houdini/runtime/query.ts
> +type QueryResponse<_Data, _Input, _Result> = {
Is this third type parameter used anywhere?

2021-05-31 16:26 UTC, AlecAivazis commented on packages/houdini/runtime/query.ts
> +		return new Promise<any>(async (resolve, reject) => {
This function shares a lot of logic with the network bits of `mutation`. I think it would be a good idea to define a function in `network.ts` with this logic to avoid the duplication.

2021-05-31 16:26 UTC, AlecAivazis commented on packages/houdini/runtime/query.ts
> +	function writeData(newData: _Query['result'], newVariables: _Query['input']) {
Just fyi, you don't need to pull this function out of the object in order to use it in another method. Here's an example: https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZiEMC8MDeBYAUDXMAWApgDbEgAUAlOtnnTFPgJYQB0A7iAE7EAmVtPAF8ANINyce-aphz1coSCGKFWZAObkA5EVIgAhFsriYQ7GazYEIVrrJUgA

I personally prefer to keep them defined in that single object literal in order to keep the block of code where the functions are defined easily referenceable

2021-05-31 16:40 UTC, pixelmund commented
Good changes! I'll try to get these in tomorrow. My dog is getting put to sleep today and I'm too sad right now.

2021-05-31 16:42 UTC, AlecAivazis commented
Oh no!!! That's awful. I'm so sorry. 

No worries at all about the changes - take your time.

2021-05-31 16:53 UTC, pixelmund commented
Thank you! At least he got very old(16, cocker spaniel) and had a happy, carefree life. Everyone has to go someday.

2021-06-01 07:52 UTC, pixelmund commented on packages/houdini/runtime/query.ts
> +	function writeData(newData: _Query['result'], newVariables: _Query['input']) {
I don't know why but this is not working for me, it is fine in this [playground](https://www.typescriptlang.org/play?alwaysStrict=false&target=99&jsx=0#code/AQ4YwewOwZwF2AMwhYBeYBvAsAKFAcAPRHBwAWApsPBAE7UzkQCuANgCbABG1DAhhwC00NgE8kdCAFsyVcPzZtKdAOQxgABxUxtYOAEsAbpTyFQHfnH4AuLMAC+AGjPngDRJThhyACipKEHbwdAZQAOYAlFiubqCQsBDKAHRsEOG+FAYwTsABaZEA3LFx7l4sdFDAUJQA7sAAClLS2ZS+-DBiUGDAvgwwSSa5DABWlPrRaAB8Mfil5iXzIAkDKWkZWTBFeItLm8m1oXCUACJW-L4AjADM17mXAEzX27i75g4vcc5vxKQsMJQuJpQtJ+KFxDwJBRqMDKMCIGBKDABnQyKgANaUOHANJgRQ0azHYBhGhdHq1AwUH4kOTUSzWYDhYyUKrcCSwtKCH6HSmnc6+Gq1M7WOxQFjSXh0XKCgBqYIM-G4yhgovFkuiODm8xWSUoqXSArqwv40rqctCiuVkR+3y1jh2duQEGSHi8Pl8qlq9E4qkiQA) but when i try to implement it i always get `Uncaught (in promise) TypeError: Cannot read property 'writeData' of undefined`. If i log `this` it is also undefined.
```js
    const foo = {
        // the store should be read-only from the caller's perspective
        data: { subscribe: store.subscribe },
        // used primarily by the preprocessor to keep local state in sync with
        // the data given by preload
        refetch(newVariables) {
            return new Promise(async (resolve, reject) => {
                let result;
                const session = get(sessionStore);
                // since we have a promise that's wrapping async/await we need a giant try/catch that will
                // reject the promise
                try {
                    const fetchCtx = {
                        fetch: window.fetch.bind(window),
                        session,
                        context: {},
                        page: {
                            host: '',
                            path: '',
                            params: {},
                            query: new URLSearchParams(),
                        },
                    };
                    // pull the query text out of the compiled artifact
                    const { raw: text } = artifact;
                    const res = await fetchQuery(fetchCtx, {
                        text,
                        // Pass the new Variables or the initial ones
                        variables: newVariables || variables,
                    }, session);
                    // we could have gotten a null response
                    if (res.errors) {
                        reject(res.errors);
                        return;
                    }
                    if (!res.data) {
                        reject([new Error('Encountered empty data response in query payload')]);
                        return;
                    }
                    result = res;
                }
                catch (e) {
                    reject(e);
                    return;
                }
                this.writeData(result, newVariables);
                resolve(result.data);
            });
        },
        writeData(newData, newVariables) {
            variables = newVariables || {};
            // make sure we list to the new data
            if (subscriptionSpec) {
                cache.subscribe(subscriptionSpec, variables);
            }
            // write the data we received
            cache.write(artifact.selection, newData.data, variables);
        },
    }
    return foo;
```

What am i missing?

2021-06-01 08:02 UTC, pixelmund commented on packages/houdini/runtime/query.ts
> +	function writeData(newData: _Query['result'], newVariables: _Query['input']) {
I found this one which explains it prelly well i think.
[https://javascript.info/object-methods](https://javascript.info/object-methods)

[Not working repro](https://www.typescriptlang.org/play?alwaysStrict=false&target=99&jsx=0#code/GYVwdgxgLglg9mABAcwKZQGJzgCgJSIDeAsAFCIWIQIDOUiw2iAvEWZR4gPReJQAWqRHTgAnITX5wQAGwAmiAEZDxAQzkBaBDICeDUXAC2fQVVUyZqUQHIaiAA5Waj6DABuqdpwpzVUVQBcRAC+ADRe3uLA6BD8OIIWcEF0ojBgyAQk5N6c4lAgokhgqADuiAAKBoYwNKg4qjQ6kIg44jRwMh6hiOIAVqjQBMwAfGzZOTkCNQB0JalQqAAifqo4AIwAzBvdawBMG3gA3BETiMFHJxxhl5Q8iCC1Cvaphqqpukp6AkLPqM9wEFQNHaoj4cEQAGtUH9EDIAeZhP4Fog0sImhBECUYAIbhQ7t9EL5-Ch3KgkIo9L84epcZj5ksVjhiiVlv4gmAQIZlKJusyAGpvGCqRSWGjsznczK0jjUMDtSzTOHIJmlVmqXmlAWpYWivC067jM5kE55ApIRhwMjBY2kWV0Ig9VDRKCxM4sFDoLC4C6kMgNdEMcCuBCO52xACSUHwWQ4qhKqmxoZicWsJTE8msetI1t9pCiycj+EOQA)

2021-06-02 02:42 UTC, plunkettscott commented
Awesome!

2021-06-02 09:48 UTC, pixelmund commented on packages/houdini/runtime/network.ts
> +	sessionStore: Readable<any>
`getSession` needs to run on component initialization, because it is using `getContext` under the hood. If we where to call getSession while executing the mutation or query afterwards it would throw an error.

2021-06-02 09:48 UTC, pixelmund commented on example/src/routes/[filter].svelte
> +		// try {
Yes it was just for testing, i will clean it up

2021-06-02 09:59 UTC, AlecAivazis commented on packages/houdini/runtime/network.ts
> +	sessionStore: Readable<any>
Makes sense!

2021-06-02 10:03 UTC, AlecAivazis commented
Thanks for getting those changes in so quickly. I'm going to take another pass at this tomorrow but I think it's ready to go.  If you don't mind taking a first pass at some documentation I can review that too otherwise I'll add something once this goes in

2021-06-02 10:05 UTC, AlecAivazis requested changes

2021-06-02 10:05 UTC, AlecAivazis commented on packages/houdini/runtime/query.ts
> +				return result.data
This shouldn't return anything, right? per the conversation in #57

2021-06-02 10:08 UTC, pixelmund commented
No problem, always happy to help. I can also review pull requests and help out if you like to add me as a maintainer or something!

2021-06-02 10:09 UTC, pixelmund commented on packages/houdini/runtime/query.ts
> +				return result.data
Ah yes, wasn't totally sure about this one.

2021-06-02 10:11 UTC, pixelmund commented
I won't have time this week to add documentation, it's the last day before holiday for me.

2021-06-06 21:43 UTC, AlecAivazis commented
Sorry this hasn't gotten merged yet! Its been a very busy week for me. I'm going to take my final pass today and get this in ASAP

2021-06-08 08:38 UTC, merged